### ISSUE TITLE
ENOENT error when running build pipeline

### ISSUE THREAD

**Issue by philipmorley** [beingnin/Azure-Devops-Extension-Sass-Compiler#5]
Hello, I am trying to use this extension to process the sass file in my solution.  Here is the exert from my azure-pipelines.yml:

```
- task: process-sass-files@0
  displayName: Compile bootstrap sass file
  inputs:
    inputFile: '$(Build.SourcesDirectory)/MyApp/wwwroot/scss/foo.scss'
    outputFile: '$(Build.SourcesDirectory)/MyApp/wwwroot/css/foo.css'
    style: 'compressed'
    enableVendorPrefixing: false
    generateSourceMap: false
```

When this runs on the Azure Dev Ops build server I get this error:

```
sass compilation thrown error
{ Error: spawn /bin/sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs:
   [ '-c',
     'sass "/home/vsts/work/1/s/MyApp/wwwroot/scss/foo.scss" "/home/vsts/work/1/s/MyApp/wwwroot/css/foo.css" --style compressed --no-source-map' ] }
##[error]Error: spawn /bin/sh ENOENT
Finishing: Compile bootstrap sass file
```

I have confirmed that the inputFile and outputFile paths exist.  I have also tried using forward-slash and back-slash characters in the path, but I keep getting to ENOENT error.  Please can you help?
